FROM nvcr.io/nvidia/isaac-sim:4.5.0

ENV DOCKER_USER_HOME=/root
ENV DEBIAN_FRONTEND=noninteractive

# Work from root
WORKDIR /

# Install utilities
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git python3 python3-pip vim cmake build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

# Environment variables
ENV ISAACSIM_PATH=/isaac-sim
ENV ISAACLAB_PATH=/IsaacLab
ENV PYTHONPATH=${ISAACLAB_PATH}/source:${PYTHONPATH}

WORKDIR /IsaacLab

# --- Install IsaacLab dependencies ---
# --- Link isaac sim ---
RUN ln -s ${ISAACSIM_PATH} _isaac_sim

WORKDIR /IsaacPanda